Updaated for pull request comment.

diff --git a/workflow-templates/im-test-k6-manual.yml b/workflow-templates/im-test-k6-manual.yml
--- a/workflow-templates/im-test-k6-manual.yml
+++ b/workflow-templates/im-test-k6-manual.yml
@@ -1,30 +1,78 @@
-name: Manual trigger K6 test - Advanced
+name: Manual trigger K6 test
 
 on: 
   workflow_dispatch:
     inputs:
+      envToTest:
+        description: 'Environment to run test against [dev, qa, stage]'   
+        required: true
+        default: 'dev'
       testFolderRoot:
         description: 'Test folder root directory from root of repo'
         required: true
-        default: "tests/k6"
+        default: "" # TODO: Verify this is the correct location of your tests.  IE: tests/k6
       testFile:
         description: 'K6 test file to run'     
         required: true
+        default: '' # TODO: Default test file  IE: check-health-simple.js
       k6_extra_params:
-        description: 'K6 commandline extra paramaters'
+        description: 'K6 command extra paramaters'
         required: false
-        default: '' # You can set default paramaters to run on K6 test. Example below:
-      
+        default: '' # TODO: Set default paramaters to run on every K6 test. IE. --vus 1 -i 1 --insecure-skip-tls-verify -out JSON="./k6-output.json" --out influxdb="http://influxdb:8086/k6" --config "/scripts/config/dev-config.json"
+      k6_version:
+        description: 'K6 version'
+        required: true
+        default: '0.33.0' # TODO: Set default verion of k6
+
 jobs:
   k6_test:
     runs-on: [self-hosted, ubuntu-20.04]
-    container: docker://loadimpact/k6:latest
 
     steps:
     - name: Checkout
       uses: actions/checkout@v1
+
+    - name: Setup K6
+      uses: im-open/setup-k6-perf-testing@v1.0.0
+      with:
+        version: ${{ github.event.inputs.k6_version }}
+
+    - name: Validate Env Input
+      id: validate-env-input
+      uses: im-open/map-input-action@v1.0.1
+      with:
+        input: ${{ github.event.inputs.envToTest }}
+        input_map: "{ \"dev\": [\"dev\", \"Dev\", \"DEV\"], \"qa\": [\"qa\", \"QA\"], \stage\": [\"stage\", \"Stage\", \"STAGE\"] }"
+        error_on_no_match: true
+        custom_error_message: "Please input a valid environment: dev,qa,stage..."
+
+    - name: Validate test file exists
+      run: |
+        echo "Checking if test file exists:" 
+        FILE="./${{ github.event.inputs.testFolderRoot }}/${{github.event.inputs.testFile}}"
+        if [[ -f $FILE ]]; then
+          echo "$FILE exists."
+        else
+          echo "Could not find test file. $FILE"
+          exit 1
+        fi
     
-    - name: Run local k6 test - docker
+    - name: Run local k6 test
       working-directory: ${{ github.event.inputs.testFolderRoot }}
       run: |
-        k6 run ${{github.event.inputs.testFile}} ${{github.event.inputs.k6_extra_params}}
+        k6 run ${{github.event.inputs.testFile}} ${{github.event.inputs.k6_extra_params}} -e RUN_ENV=${{steps.validate-env-input.mapped_input}}
+
+    # TODO: Run this step for Stress test workflow.  Uncomment this step and delete/comment out the step above.
+    # - name: Run local k6 stress test
+    #   working-directory: ${{ github.event.inputs.testFolderRoot }}
+    #   run: |
+    #     # ulimit must be set in k6 step as it gets reset every session.
+    #     # The nofile limit cannot exceed the hard limit.  You will get a permission denied if you do.
+    #     ulimit -n 1048576
+    #     echo "Open Files, Reuse TCP ports, and Port Range below:"
+    #     ulimit -Sa | grep 'open files'
+    #     sudo sysctl -a | grep -E 'net.ipv4.ip_local_port_range|net.ipv4.tcp_tw_reuse|fs.file-max'
+    #     k6 run ${{github.event.inputs.testFile}} ${{github.event.inputs.k6_extra_params}} -e RUN_ENV=${{steps.validate-env-input.mapped_input}}
+
+
+     
